language: ruby
rvm:
- 2.1.2
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- cp config/database.travis.yml config/database.yml
script:
- bundle exec rake db:drop:all
- bundle exec rake db:create:all
- bundle exec rake db:schema:load
- bundle exec rake --trace
deploy:
  provider: heroku
  api_key:
    secure: iq7Dg8MvCYyNStfm8kXf/VTmsHToRD7u1YOdNJBvx0cNemlzNoEk2aIUgqVX+cTnrssWpeu27GrW2B1Lw5iiJ5uV+OcBDasR1DDN4NFMOzTJI9a0Q+H5SWfibcINcK1LkElGr/foiWGgzac3G2tSa90xIEQupPj6j01AZ1VmM78=
  app: denver-startup-week
  on:
    repo: modeset/denver-startup-week
    branch: master
