language: ruby
sudo: false
rvm:
- 2.3.0
services:
- redis-server
bundler_args:
  --without development production
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- cp config/database.travis.yml config/database.yml
- cp .env.example .env
script:
- bundle exec rake db:setup spec
